// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: atom.proto
// Protobuf C++ Version: 6.31.1

#include "atom.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace mal {
namespace proto {

inline constexpr MALAtomField::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        extra_val_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pos_{::int64_t{0}},
        bits_{0},
        big_{0},
        type_{static_cast< ::mal::proto::MDPFieldDisplayType >(0)},
        typevalue_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR MALAtomField::MALAtomField(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MALAtomField_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MALAtomFieldDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MALAtomFieldDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MALAtomFieldDefaultTypeInternal() {}
  union {
    MALAtomField _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MALAtomFieldDefaultTypeInternal _MALAtomField_default_instance_;

inline constexpr MALAtom::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        fields_{},
        child_boxes_{},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pos_{::int64_t{0}},
        size_{::int64_t{0}},
        header_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MALAtom::MALAtom(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MALAtom_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MALAtomDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MALAtomDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MALAtomDefaultTypeInternal() {}
  union {
    MALAtom _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MALAtomDefaultTypeInternal _MALAtom_default_instance_;
}  // namespace proto
}  // namespace mal
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_atom_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_atom_2eproto = nullptr;
const ::uint32_t
    TableStruct_atom_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x085, // bitmap
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtomField, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtomField, _impl_._oneof_case_[0]),
        18, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtomField, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtomField, _impl_.pos_),
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtomField, _impl_.bits_),
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtomField, _impl_.extra_val_),
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtomField, _impl_.big_),
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtomField, _impl_.value_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtomField, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtomField, _impl_.typevalue_),
        0,
        3,
        4,
        1,
        5,
        2,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        6,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtom, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtom, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtom, _impl_.pos_),
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtom, _impl_.size_),
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtom, _impl_.fields_),
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtom, _impl_.child_boxes_),
        PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtom, _impl_.header_size_),
        0,
        1,
        2,
        ~0u,
        ~0u,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::mal::proto::MALAtomField)},
        {31, sizeof(::mal::proto::MALAtom)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::mal::proto::_MALAtomField_default_instance_._instance,
    &::mal::proto::_MALAtom_default_instance_._instance,
};
const char descriptor_table_protodef_atom_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\natom.proto\022\tmal.proto\"\375\001\n\014MALAtomField"
    "\022\014\n\004name\030\001 \001(\t\022\013\n\003pos\030\002 \001(\003\022\014\n\004bits\030\003 \001("
    "\005\022\021\n\textra_val\030\004 \001(\t\022\013\n\003big\030\005 \001(\005\022\r\n\005val"
    "ue\030\007 \001(\t\022\r\n\003i32\030\010 \001(\005H\000\022\r\n\003i64\030\t \001(\003H\000\022\016"
    "\n\004ui32\030\n \001(\rH\000\022\016\n\004ui64\030\013 \001(\004H\000\022\014\n\002db\030\014 \001"
    "(\001H\000\022\016\n\004strv\030\r \001(\tH\000\022,\n\004type\030\016 \001(\0162\036.mal"
    ".proto.MDPFieldDisplayTypeB\013\n\ttypevalue\""
    "\231\001\n\007MALAtom\022\014\n\004name\030\001 \001(\t\022\013\n\003pos\030\002 \001(\003\022\014"
    "\n\004size\030\003 \001(\003\022\'\n\006fields\030\004 \003(\0132\027.mal.proto"
    ".MALAtomField\022\'\n\013child_boxes\030\005 \003(\0132\022.mal"
    ".proto.MALAtom\022\023\n\013header_size\030\006 \001(\005*\212\001\n\023"
    "MDPFieldDisplayType\022\t\n\005int64\020\000\022\n\n\006string"
    "\020\001\022\r\n\tseparator\020\002\022\007\n\003hex\020\003\022\n\n\006double\020\004\022\025"
    "\n\021fixed_16X16_float\020\005\022\t\n\005int32\020\006\022\n\n\006uint"
    "32\020\007\022\n\n\006uint64\020\010b\006proto3"
};
static ::absl::once_flag descriptor_table_atom_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_atom_2eproto = {
    false,
    false,
    584,
    descriptor_table_protodef_atom_2eproto,
    "atom.proto",
    &descriptor_table_atom_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_atom_2eproto::offsets,
    file_level_enum_descriptors_atom_2eproto,
    file_level_service_descriptors_atom_2eproto,
};
namespace mal {
namespace proto {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MDPFieldDisplayType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_atom_2eproto);
  return file_level_enum_descriptors_atom_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t MDPFieldDisplayType_internal_data_[] = {
    589824u, 0u, };
// ===================================================================

class MALAtomField::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<MALAtomField>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::mal::proto::MALAtomField, _impl_._oneof_case_);
};

MALAtomField::MALAtomField(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MALAtomField_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mal.proto.MALAtomField)
}
PROTOBUF_NDEBUG_INLINE MALAtomField::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::mal::proto::MALAtomField& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_),
        extra_val_(arena, from.extra_val_),
        value_(arena, from.value_),
        typevalue_{},
        _oneof_case_{from._oneof_case_[0]} {}

MALAtomField::MALAtomField(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const MALAtomField& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MALAtomField_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MALAtomField* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pos_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, pos_),
           offsetof(Impl_, type_) -
               offsetof(Impl_, pos_) +
               sizeof(Impl_::type_));
  switch (typevalue_case()) {
    case TYPEVALUE_NOT_SET:
      break;
      case kI32:
        _impl_.typevalue_.i32_ = from._impl_.typevalue_.i32_;
        break;
      case kI64:
        _impl_.typevalue_.i64_ = from._impl_.typevalue_.i64_;
        break;
      case kUi32:
        _impl_.typevalue_.ui32_ = from._impl_.typevalue_.ui32_;
        break;
      case kUi64:
        _impl_.typevalue_.ui64_ = from._impl_.typevalue_.ui64_;
        break;
      case kDb:
        _impl_.typevalue_.db_ = from._impl_.typevalue_.db_;
        break;
      case kStrv:
        new (&_impl_.typevalue_.strv_) decltype(_impl_.typevalue_.strv_){arena, from._impl_.typevalue_.strv_};
        break;
  }

  // @@protoc_insertion_point(copy_constructor:mal.proto.MALAtomField)
}
PROTOBUF_NDEBUG_INLINE MALAtomField::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena),
        extra_val_(arena),
        value_(arena),
        typevalue_{},
        _oneof_case_{} {}

inline void MALAtomField::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pos_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, pos_) +
               sizeof(Impl_::type_));
}
MALAtomField::~MALAtomField() {
  // @@protoc_insertion_point(destructor:mal.proto.MALAtomField)
  SharedDtor(*this);
}
inline void MALAtomField::SharedDtor(MessageLite& self) {
  MALAtomField& this_ = static_cast<MALAtomField&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.extra_val_.Destroy();
  this_._impl_.value_.Destroy();
  if (this_.has_typevalue()) {
    this_.clear_typevalue();
  }
  this_._impl_.~Impl_();
}

void MALAtomField::clear_typevalue() {
// @@protoc_insertion_point(one_of_clear_start:mal.proto.MALAtomField)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (typevalue_case()) {
    case kI32: {
      // No need to clear
      break;
    }
    case kI64: {
      // No need to clear
      break;
    }
    case kUi32: {
      // No need to clear
      break;
    }
    case kUi64: {
      // No need to clear
      break;
    }
    case kDb: {
      // No need to clear
      break;
    }
    case kStrv: {
      _impl_.typevalue_.strv_.Destroy();
      break;
    }
    case TYPEVALUE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = TYPEVALUE_NOT_SET;
}


inline void* PROTOBUF_NONNULL MALAtomField::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MALAtomField(arena);
}
constexpr auto MALAtomField::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MALAtomField),
                                            alignof(MALAtomField));
}
constexpr auto MALAtomField::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MALAtomField_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MALAtomField::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MALAtomField>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MALAtomField::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MALAtomField>(), &MALAtomField::ByteSizeLong,
              &MALAtomField::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_._cached_size_),
          false,
      },
      &MALAtomField::kDescriptorMethods,
      &descriptor_table_atom_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MALAtomField_class_data_ =
        MALAtomField::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
MALAtomField::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MALAtomField_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MALAtomField_class_data_.tc_table);
  return MALAtomField_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 13, 0, 61, 2>
MALAtomField::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_._has_bits_),
    0, // no _extensions_
    14, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294950944,  // skipmap
    offsetof(decltype(_table_), field_entries),
    13,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    MALAtomField_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mal::proto::MALAtomField>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.name_)}},
    // int64 pos = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MALAtomField, _impl_.pos_), 3>(),
     {16, 3, 0, PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.pos_)}},
    // int32 bits = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MALAtomField, _impl_.bits_), 4>(),
     {24, 4, 0, PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.bits_)}},
    // string extra_val = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0, PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.extra_val_)}},
    // int32 big = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MALAtomField, _impl_.big_), 5>(),
     {40, 5, 0, PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.big_)}},
    // .mal.proto.MDPFieldDisplayType type = 14;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MALAtomField, _impl_.type_), 6>(),
     {112, 6, 0, PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.type_)}},
    // string value = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 2, 0, PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 pos = 2;
    {PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.pos_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int32 bits = 3;
    {PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.bits_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string extra_val = 4;
    {PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.extra_val_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 big = 5;
    {PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.big_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string value = 7;
    {PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.value_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 i32 = 8;
    {PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.typevalue_.i32_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt32)},
    // int64 i64 = 9;
    {PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.typevalue_.i64_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt64)},
    // uint32 ui32 = 10;
    {PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.typevalue_.ui32_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUInt32)},
    // uint64 ui64 = 11;
    {PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.typevalue_.ui64_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUInt64)},
    // double db = 12;
    {PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.typevalue_.db_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kDouble)},
    // string strv = 13;
    {PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.typevalue_.strv_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .mal.proto.MDPFieldDisplayType type = 14;
    {PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.type_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\26\4\0\0\11\0\5\0\0\0\0\0\4\0\0\0"
    "mal.proto.MALAtomField"
    "name"
    "extra_val"
    "value"
    "strv"
  }},
};
PROTOBUF_NOINLINE void MALAtomField::Clear() {
// @@protoc_insertion_point(message_clear_start:mal.proto.MALAtomField)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.extra_val_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _impl_.value_.ClearNonDefaultToEmpty();
    }
  }
  if ((cached_has_bits & 0x00000078u) != 0) {
    ::memset(&_impl_.pos_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.type_) -
        reinterpret_cast<char*>(&_impl_.pos_)) + sizeof(_impl_.type_));
  }
  clear_typevalue();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MALAtomField::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MALAtomField& this_ = static_cast<const MALAtomField&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MALAtomField::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MALAtomField& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:mal.proto.MALAtomField)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mal.proto.MALAtomField.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int64 pos = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (this_._internal_pos() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_pos(), target);
    }
  }

  // int32 bits = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000010u) != 0) {
    if (this_._internal_bits() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_bits(), target);
    }
  }

  // string extra_val = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_extra_val().empty()) {
      const ::std::string& _s = this_._internal_extra_val();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mal.proto.MALAtomField.extra_val");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // int32 big = 5;
  if ((this_._impl_._has_bits_[0] & 0x00000020u) != 0) {
    if (this_._internal_big() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
              stream, this_._internal_big(), target);
    }
  }

  // string value = 7;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (!this_._internal_value().empty()) {
      const ::std::string& _s = this_._internal_value();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mal.proto.MALAtomField.value");
      target = stream->WriteStringMaybeAliased(7, _s, target);
    }
  }

  switch (this_.typevalue_case()) {
    case kI32: {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<8>(
              stream, this_._internal_i32(), target);
      break;
    }
    case kI64: {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<9>(
              stream, this_._internal_i64(), target);
      break;
    }
    case kUi32: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          10, this_._internal_ui32(), target);
      break;
    }
    case kUi64: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          11, this_._internal_ui64(), target);
      break;
    }
    case kDb: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          12, this_._internal_db(), target);
      break;
    }
    case kStrv: {
      const ::std::string& _s = this_._internal_strv();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mal.proto.MALAtomField.strv");
      target = stream->WriteStringMaybeAliased(13, _s, target);
      break;
    }
    default:
      break;
  }
  // .mal.proto.MDPFieldDisplayType type = 14;
  if ((this_._impl_._has_bits_[0] & 0x00000040u) != 0) {
    if (this_._internal_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          14, this_._internal_type(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mal.proto.MALAtomField)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MALAtomField::ByteSizeLong(const MessageLite& base) {
  const MALAtomField& this_ = static_cast<const MALAtomField&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MALAtomField::ByteSizeLong() const {
  const MALAtomField& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mal.proto.MALAtomField)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000007fu) != 0) {
    // string name = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
    // string extra_val = 4;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_extra_val().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_extra_val());
      }
    }
    // string value = 7;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!this_._internal_value().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_value());
      }
    }
    // int64 pos = 2;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (this_._internal_pos() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_pos());
      }
    }
    // int32 bits = 3;
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (this_._internal_bits() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_bits());
      }
    }
    // int32 big = 5;
    if ((cached_has_bits & 0x00000020u) != 0) {
      if (this_._internal_big() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_big());
      }
    }
    // .mal.proto.MDPFieldDisplayType type = 14;
    if ((cached_has_bits & 0x00000040u) != 0) {
      if (this_._internal_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
      }
    }
  }
  switch (this_.typevalue_case()) {
    // int32 i32 = 8;
    case kI32: {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_i32());
      break;
    }
    // int64 i64 = 9;
    case kI64: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_i64());
      break;
    }
    // uint32 ui32 = 10;
    case kUi32: {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_ui32());
      break;
    }
    // uint64 ui64 = 11;
    case kUi64: {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_ui64());
      break;
    }
    // double db = 12;
    case kDb: {
      total_size += 9;
      break;
    }
    // string strv = 13;
    case kStrv: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_strv());
      break;
    }
    case TYPEVALUE_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MALAtomField::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MALAtomField*>(&to_msg);
  auto& from = static_cast<const MALAtomField&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:mal.proto.MALAtomField)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000007fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_extra_val().empty()) {
        _this->_internal_set_extra_val(from._internal_extra_val());
      } else {
        if (_this->_impl_.extra_val_.IsDefault()) {
          _this->_internal_set_extra_val("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!from._internal_value().empty()) {
        _this->_internal_set_value(from._internal_value());
      } else {
        if (_this->_impl_.value_.IsDefault()) {
          _this->_internal_set_value("");
        }
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (from._internal_pos() != 0) {
        _this->_impl_.pos_ = from._impl_.pos_;
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (from._internal_bits() != 0) {
        _this->_impl_.bits_ = from._impl_.bits_;
      }
    }
    if ((cached_has_bits & 0x00000020u) != 0) {
      if (from._internal_big() != 0) {
        _this->_impl_.big_ = from._impl_.big_;
      }
    }
    if ((cached_has_bits & 0x00000040u) != 0) {
      if (from._internal_type() != 0) {
        _this->_impl_.type_ = from._impl_.type_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_typevalue();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kI32: {
        _this->_impl_.typevalue_.i32_ = from._impl_.typevalue_.i32_;
        break;
      }
      case kI64: {
        _this->_impl_.typevalue_.i64_ = from._impl_.typevalue_.i64_;
        break;
      }
      case kUi32: {
        _this->_impl_.typevalue_.ui32_ = from._impl_.typevalue_.ui32_;
        break;
      }
      case kUi64: {
        _this->_impl_.typevalue_.ui64_ = from._impl_.typevalue_.ui64_;
        break;
      }
      case kDb: {
        _this->_impl_.typevalue_.db_ = from._impl_.typevalue_.db_;
        break;
      }
      case kStrv: {
        if (oneof_needs_init) {
          _this->_impl_.typevalue_.strv_.InitDefault();
        }
        _this->_impl_.typevalue_.strv_.Set(from._internal_strv(), arena);
        break;
      }
      case TYPEVALUE_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MALAtomField::CopyFrom(const MALAtomField& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mal.proto.MALAtomField)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MALAtomField::InternalSwap(MALAtomField* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.extra_val_, &other->_impl_.extra_val_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.type_)
      + sizeof(MALAtomField::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(MALAtomField, _impl_.pos_)>(
          reinterpret_cast<char*>(&_impl_.pos_),
          reinterpret_cast<char*>(&other->_impl_.pos_));
  swap(_impl_.typevalue_, other->_impl_.typevalue_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata MALAtomField::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MALAtom::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<MALAtom>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MALAtom, _impl_._has_bits_);
};

MALAtom::MALAtom(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MALAtom_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mal.proto.MALAtom)
}
PROTOBUF_NDEBUG_INLINE MALAtom::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::mal::proto::MALAtom& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        fields_{visibility, arena, from.fields_},
        child_boxes_{visibility, arena, from.child_boxes_},
        name_(arena, from.name_) {}

MALAtom::MALAtom(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const MALAtom& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MALAtom_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MALAtom* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pos_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, pos_),
           offsetof(Impl_, header_size_) -
               offsetof(Impl_, pos_) +
               sizeof(Impl_::header_size_));

  // @@protoc_insertion_point(copy_constructor:mal.proto.MALAtom)
}
PROTOBUF_NDEBUG_INLINE MALAtom::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        fields_{visibility, arena},
        child_boxes_{visibility, arena},
        name_(arena) {}

inline void MALAtom::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pos_),
           0,
           offsetof(Impl_, header_size_) -
               offsetof(Impl_, pos_) +
               sizeof(Impl_::header_size_));
}
MALAtom::~MALAtom() {
  // @@protoc_insertion_point(destructor:mal.proto.MALAtom)
  SharedDtor(*this);
}
inline void MALAtom::SharedDtor(MessageLite& self) {
  MALAtom& this_ = static_cast<MALAtom&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MALAtom::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MALAtom(arena);
}
constexpr auto MALAtom::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.fields_) +
          decltype(MALAtom::_impl_.fields_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.child_boxes_) +
          decltype(MALAtom::_impl_.child_boxes_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(MALAtom), alignof(MALAtom), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&MALAtom::PlacementNew_,
                                 sizeof(MALAtom),
                                 alignof(MALAtom));
  }
}
constexpr auto MALAtom::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MALAtom_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MALAtom::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MALAtom>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MALAtom::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MALAtom>(), &MALAtom::ByteSizeLong,
              &MALAtom::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MALAtom, _impl_._cached_size_),
          false,
      },
      &MALAtom::kDescriptorMethods,
      &descriptor_table_atom_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MALAtom_class_data_ =
        MALAtom::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
MALAtom::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MALAtom_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MALAtom_class_data_.tc_table);
  return MALAtom_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 2, 30, 2>
MALAtom::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MALAtom, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    MALAtom_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mal::proto::MALAtom>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.name_)}},
    // int64 pos = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MALAtom, _impl_.pos_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.pos_)}},
    // int64 size = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MALAtom, _impl_.size_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.size_)}},
    // repeated .mal.proto.MALAtomField fields = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.fields_)}},
    // repeated .mal.proto.MALAtom child_boxes = 5;
    {::_pbi::TcParser::FastMtR1,
     {42, 63, 1, PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.child_boxes_)}},
    // int32 header_size = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MALAtom, _impl_.header_size_), 3>(),
     {48, 3, 0, PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.header_size_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 pos = 2;
    {PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.pos_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int64 size = 3;
    {PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.size_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // repeated .mal.proto.MALAtomField fields = 4;
    {PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.fields_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .mal.proto.MALAtom child_boxes = 5;
    {PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.child_boxes_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // int32 header_size = 6;
    {PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.header_size_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::mal::proto::MALAtomField>()},
      {::_pbi::TcParser::GetTable<::mal::proto::MALAtom>()},
  }},
  {{
    "\21\4\0\0\0\0\0\0"
    "mal.proto.MALAtom"
    "name"
  }},
};
PROTOBUF_NOINLINE void MALAtom::Clear() {
// @@protoc_insertion_point(message_clear_start:mal.proto.MALAtom)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.fields_.Clear();
  _impl_.child_boxes_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  if ((cached_has_bits & 0x0000000eu) != 0) {
    ::memset(&_impl_.pos_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.header_size_) -
        reinterpret_cast<char*>(&_impl_.pos_)) + sizeof(_impl_.header_size_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MALAtom::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MALAtom& this_ = static_cast<const MALAtom&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MALAtom::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MALAtom& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:mal.proto.MALAtom)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mal.proto.MALAtom.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int64 pos = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_pos() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_pos(), target);
    }
  }

  // int64 size = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_size() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
              stream, this_._internal_size(), target);
    }
  }

  // repeated .mal.proto.MALAtomField fields = 4;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_fields_size());
       i < n; i++) {
    const auto& repfield = this_._internal_fields().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            4, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // repeated .mal.proto.MALAtom child_boxes = 5;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_child_boxes_size());
       i < n; i++) {
    const auto& repfield = this_._internal_child_boxes().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            5, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // int32 header_size = 6;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (this_._internal_header_size() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<6>(
              stream, this_._internal_header_size(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mal.proto.MALAtom)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MALAtom::ByteSizeLong(const MessageLite& base) {
  const MALAtom& this_ = static_cast<const MALAtom&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MALAtom::ByteSizeLong() const {
  const MALAtom& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mal.proto.MALAtom)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .mal.proto.MALAtomField fields = 4;
    {
      total_size += 1UL * this_._internal_fields_size();
      for (const auto& msg : this_._internal_fields()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .mal.proto.MALAtom child_boxes = 5;
    {
      total_size += 1UL * this_._internal_child_boxes_size();
      for (const auto& msg : this_._internal_child_boxes()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    // string name = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
    // int64 pos = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_pos() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_pos());
      }
    }
    // int64 size = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_size() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_size());
      }
    }
    // int32 header_size = 6;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (this_._internal_header_size() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_header_size());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MALAtom::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MALAtom*>(&to_msg);
  auto& from = static_cast<const MALAtom&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mal.proto.MALAtom)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_fields()->MergeFrom(
      from._internal_fields());
  _this->_internal_mutable_child_boxes()->MergeFrom(
      from._internal_child_boxes());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_pos() != 0) {
        _this->_impl_.pos_ = from._impl_.pos_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_size() != 0) {
        _this->_impl_.size_ = from._impl_.size_;
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (from._internal_header_size() != 0) {
        _this->_impl_.header_size_ = from._impl_.header_size_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MALAtom::CopyFrom(const MALAtom& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mal.proto.MALAtom)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MALAtom::InternalSwap(MALAtom* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.fields_.InternalSwap(&other->_impl_.fields_);
  _impl_.child_boxes_.InternalSwap(&other->_impl_.child_boxes_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.header_size_)
      + sizeof(MALAtom::_impl_.header_size_)
      - PROTOBUF_FIELD_OFFSET(MALAtom, _impl_.pos_)>(
          reinterpret_cast<char*>(&_impl_.pos_),
          reinterpret_cast<char*>(&other->_impl_.pos_));
}

::google::protobuf::Metadata MALAtom::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace mal
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_atom_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
