// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: atom.proto
// Protobuf C++ Version: 7.36.0-dev

#ifndef atom_2eproto_2epb_2eh
#define atom_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_atom_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_atom_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_atom_2eproto;
}  // extern "C"
namespace mal {
namespace proto {
enum MDPFieldDisplayType : int;
extern const uint32_t MDPFieldDisplayType_internal_data_[];
class MALAtom;
struct MALAtomGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern MALAtomGlobalsTypeInternal MALAtom_globals_;
extern const ::google::protobuf::internal::ClassDataFull MALAtom_class_data_;
#else
extern const MALAtomGlobalsTypeInternal MALAtom_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class MALAtomField;
struct MALAtomFieldGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern MALAtomFieldGlobalsTypeInternal MALAtomField_globals_;
extern const ::google::protobuf::internal::ClassDataFull MALAtomField_class_data_;
#else
extern const MALAtomFieldGlobalsTypeInternal MALAtomField_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace proto
}  // namespace mal
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::mal::proto::MDPFieldDisplayType_internal_data_>
    internal::EnumTraitsImpl::value<::mal::proto::MDPFieldDisplayType>;
}  // namespace protobuf
}  // namespace google

namespace mal {
namespace proto {
enum MDPFieldDisplayType : int {
  int64 = 0,
  string = 1,
  separator = 2,
  hex = 3,
  double_ = 4,
  fixed_16X16_float = 5,
  int32 = 6,
  uint32 = 7,
  uint64 = 8,
  MDPFieldDisplayType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  MDPFieldDisplayType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t MDPFieldDisplayType_internal_data_[];
inline constexpr MDPFieldDisplayType MDPFieldDisplayType_MIN =
    static_cast<MDPFieldDisplayType>(0);
inline constexpr MDPFieldDisplayType MDPFieldDisplayType_MAX =
    static_cast<MDPFieldDisplayType>(8);
[[nodiscard]] inline bool MDPFieldDisplayType_IsValid(int value) {
  return 0 <= value && value <= 8;
}
inline constexpr int MDPFieldDisplayType_ARRAYSIZE = 8 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
MDPFieldDisplayType_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(MDPFieldDisplayType) {
  return MDPFieldDisplayType_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& MDPFieldDisplayType_Name(T value) {
  static_assert(::std::is_same<T, MDPFieldDisplayType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to MDPFieldDisplayType_Name().");
  return MDPFieldDisplayType_Name(static_cast<MDPFieldDisplayType>(value));
}
template <>
[[nodiscard]] inline const ::std::string& MDPFieldDisplayType_Name(MDPFieldDisplayType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<MDPFieldDisplayType_descriptor, 0, 8>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool MDPFieldDisplayType_Parse(
    ::absl::string_view name, MDPFieldDisplayType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<MDPFieldDisplayType>(MDPFieldDisplayType_descriptor(), name,
                                           value);
}
using ::google::protobuf::internal::generated_enum::AbslParseFlag;
using ::google::protobuf::internal::generated_enum::AbslUnparseFlag;

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED MALAtomField final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mal.proto.MALAtomField) */ {
 public:
  inline MALAtomField() : MALAtomField(nullptr) {}
  ~MALAtomField() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MALAtomField* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MALAtomField));
  }
#endif

  template <typename = void>
  explicit constexpr MALAtomField(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline MALAtomField(const MALAtomField& from) : MALAtomField(nullptr, from) {}
  inline MALAtomField(MALAtomField&& from) noexcept : MALAtomField(nullptr, ::std::move(from)) {}
  inline MALAtomField& operator=(const MALAtomField& from) {
    CopyFrom(from);
    return *this;
  }
  inline MALAtomField& operator=(MALAtomField&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const MALAtomField& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<MALAtomField>(&MALAtomField_globals_);
  }
  enum TypevalueCase {
    kI32 = 8,
    kI64 = 9,
    kUi32 = 10,
    kUi64 = 11,
    kDb = 12,
    kStrv = 13,
    TYPEVALUE_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MALAtomField& a, MALAtomField& b) { a.Swap(&b); }
  inline void Swap(MALAtomField* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MALAtomField* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] MALAtomField* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MALAtomField>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MALAtomField& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MALAtomField& from) { MALAtomField::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MALAtomField* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mal.proto.MALAtomField"; }

  explicit MALAtomField(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MALAtomField(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MALAtomField& from);
  MALAtomField(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MALAtomField&& from) noexcept
      : MALAtomField(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kExtraValFieldNumber = 4,
    kValueFieldNumber = 7,
    kPosFieldNumber = 2,
    kBitsFieldNumber = 3,
    kBigFieldNumber = 5,
    kTypeFieldNumber = 14,
    kI32FieldNumber = 8,
    kI64FieldNumber = 9,
    kUi32FieldNumber = 10,
    kUi64FieldNumber = 11,
    kDbFieldNumber = 12,
    kStrvFieldNumber = 13,
  };
  // string name = 1;
  void clear_name() ;
  [[nodiscard]] const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // string extra_val = 4;
  void clear_extra_val() ;
  [[nodiscard]] const ::std::string& extra_val() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_extra_val(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_extra_val();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_extra_val();
  void set_allocated_extra_val(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_extra_val() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_extra_val(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_extra_val();

  public:
  // string value = 7;
  void clear_value() ;
  [[nodiscard]] const ::std::string& value() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_value(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_value();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_value();
  void set_allocated_value(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_value() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_value(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_value();

  public:
  // int64 pos = 2;
  void clear_pos() ;
  [[nodiscard]] ::int64_t pos() const;
  void set_pos(::int64_t value);

  private:
  ::int64_t _internal_pos() const;
  void _internal_set_pos(::int64_t value);

  public:
  // int32 bits = 3;
  void clear_bits() ;
  [[nodiscard]] ::int32_t bits() const;
  void set_bits(::int32_t value);

  private:
  ::int32_t _internal_bits() const;
  void _internal_set_bits(::int32_t value);

  public:
  // int32 big = 5;
  void clear_big() ;
  [[nodiscard]] ::int32_t big() const;
  void set_big(::int32_t value);

  private:
  ::int32_t _internal_big() const;
  void _internal_set_big(::int32_t value);

  public:
  // .mal.proto.MDPFieldDisplayType type = 14;
  void clear_type() ;
  [[nodiscard]] ::mal::proto::MDPFieldDisplayType type() const;
  void set_type(::mal::proto::MDPFieldDisplayType value);

  private:
  ::mal::proto::MDPFieldDisplayType _internal_type() const;
  void _internal_set_type(::mal::proto::MDPFieldDisplayType value);

  public:
  // int32 i32 = 8;
  [[nodiscard]] bool has_i32() const;
  void clear_i32() ;
  [[nodiscard]] ::int32_t i32() const;
  void set_i32(::int32_t value);

  private:
  ::int32_t _internal_i32() const;
  void _internal_set_i32(::int32_t value);

  public:
  // int64 i64 = 9;
  [[nodiscard]] bool has_i64() const;
  void clear_i64() ;
  [[nodiscard]] ::int64_t i64() const;
  void set_i64(::int64_t value);

  private:
  ::int64_t _internal_i64() const;
  void _internal_set_i64(::int64_t value);

  public:
  // uint32 ui32 = 10;
  [[nodiscard]] bool has_ui32() const;
  void clear_ui32() ;
  [[nodiscard]] ::uint32_t ui32() const;
  void set_ui32(::uint32_t value);

  private:
  ::uint32_t _internal_ui32() const;
  void _internal_set_ui32(::uint32_t value);

  public:
  // uint64 ui64 = 11;
  [[nodiscard]] bool has_ui64() const;
  void clear_ui64() ;
  [[nodiscard]] ::uint64_t ui64() const;
  void set_ui64(::uint64_t value);

  private:
  ::uint64_t _internal_ui64() const;
  void _internal_set_ui64(::uint64_t value);

  public:
  // double db = 12;
  [[nodiscard]] bool has_db() const;
  void clear_db() ;
  [[nodiscard]] double db() const;
  void set_db(double value);

  private:
  double _internal_db() const;
  void _internal_set_db(double value);

  public:
  // string strv = 13;
  [[nodiscard]] bool has_strv() const;
  void clear_strv() ;
  [[nodiscard]] const ::std::string& strv() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_strv(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_strv();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_strv();
  void set_allocated_strv(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_strv() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_strv(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_strv();

  public:
  void clear_typevalue();
  TypevalueCase typevalue_case() const;
  // @@protoc_insertion_point(class_scope:mal.proto.MALAtomField)
 private:
  class _Internal;
  void set_has_i32();
  void set_has_i64();
  void set_has_ui32();
  void set_has_ui64();
  void set_has_db();
  void set_has_strv();
  [[nodiscard]] inline bool has_typevalue() const;
  inline void clear_has_typevalue();
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 13,
                          0, 61,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MALAtomField& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr extra_val_;
    ::google::protobuf::internal::ArenaStringPtr value_;
    ::int64_t pos_;
    ::int32_t bits_;
    ::int32_t big_;
    int type_;
    union TypevalueUnion {
      constexpr TypevalueUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::int32_t i32_;
      ::int64_t i64_;
      ::uint32_t ui32_;
      ::uint64_t ui64_;
      double db_;
      ::google::protobuf::internal::ArenaStringPtr strv_;
    } typevalue_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_atom_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED MALAtom final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mal.proto.MALAtom) */ {
 public:
  inline MALAtom() : MALAtom(nullptr) {}
  ~MALAtom() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MALAtom* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MALAtom));
  }
#endif

  template <typename = void>
  explicit constexpr MALAtom(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline MALAtom(const MALAtom& from) : MALAtom(nullptr, from) {}
  inline MALAtom(MALAtom&& from) noexcept : MALAtom(nullptr, ::std::move(from)) {}
  inline MALAtom& operator=(const MALAtom& from) {
    CopyFrom(from);
    return *this;
  }
  inline MALAtom& operator=(MALAtom&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const MALAtom& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<MALAtom>(&MALAtom_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(MALAtom& a, MALAtom& b) { a.Swap(&b); }
  inline void Swap(MALAtom* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MALAtom* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] MALAtom* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MALAtom>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MALAtom& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MALAtom& from) { MALAtom::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MALAtom* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mal.proto.MALAtom"; }

  explicit MALAtom(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MALAtom(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MALAtom& from);
  MALAtom(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MALAtom&& from) noexcept
      : MALAtom(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFieldsFieldNumber = 4,
    kChildBoxesFieldNumber = 5,
    kNameFieldNumber = 1,
    kPosFieldNumber = 2,
    kSizeFieldNumber = 3,
    kHeaderSizeFieldNumber = 6,
  };
  // repeated .mal.proto.MALAtomField fields = 4;
  [[nodiscard]] int fields_size() const;
  private:
  int _internal_fields_size() const;

  public:
  void clear_fields() ;
  [[nodiscard]] const ::mal::proto::MALAtomField& fields(int index) const;
  [[nodiscard]] ::mal::proto::MALAtomField* PROTOBUF_NONNULL mutable_fields(int index);
  ::mal::proto::MALAtomField* PROTOBUF_NONNULL add_fields();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtomField>&
  fields() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtomField>* PROTOBUF_NONNULL
  mutable_fields();

  private:
  const ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtomField>& _internal_fields() const;
  ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtomField>* PROTOBUF_NONNULL _internal_mutable_fields();

  public:
  // repeated .mal.proto.MALAtom child_boxes = 5;
  [[nodiscard]] int child_boxes_size() const;
  private:
  int _internal_child_boxes_size() const;

  public:
  void clear_child_boxes() ;
  [[nodiscard]] const ::mal::proto::MALAtom& child_boxes(int index) const;
  [[nodiscard]] ::mal::proto::MALAtom* PROTOBUF_NONNULL mutable_child_boxes(int index);
  ::mal::proto::MALAtom* PROTOBUF_NONNULL add_child_boxes();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtom>&
  child_boxes() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtom>* PROTOBUF_NONNULL
  mutable_child_boxes();

  private:
  const ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtom>& _internal_child_boxes() const;
  ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtom>* PROTOBUF_NONNULL _internal_mutable_child_boxes();

  public:
  // string name = 1;
  void clear_name() ;
  [[nodiscard]] const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // int64 pos = 2;
  void clear_pos() ;
  [[nodiscard]] ::int64_t pos() const;
  void set_pos(::int64_t value);

  private:
  ::int64_t _internal_pos() const;
  void _internal_set_pos(::int64_t value);

  public:
  // int64 size = 3;
  void clear_size() ;
  [[nodiscard]] ::int64_t size() const;
  void set_size(::int64_t value);

  private:
  ::int64_t _internal_size() const;
  void _internal_set_size(::int64_t value);

  public:
  // int32 header_size = 6;
  void clear_header_size() ;
  [[nodiscard]] ::int32_t header_size() const;
  void set_header_size(::int32_t value);

  private:
  ::int32_t _internal_header_size() const;
  void _internal_set_header_size(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mal.proto.MALAtom)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 6,
                          2, 30,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MALAtom& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::mal::proto::MALAtomField > fields_;
    ::google::protobuf::RepeatedPtrField< ::mal::proto::MALAtom > child_boxes_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::int64_t pos_;
    ::int64_t size_;
    ::int32_t header_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_atom_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MALAtomField

// string name = 1;
inline void MALAtomField::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& MALAtomField::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtomField.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MALAtomField::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mal.proto.MALAtomField.name)
}
inline ::std::string* PROTOBUF_NONNULL MALAtomField::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:mal.proto.MALAtomField.name)
  return _s;
}
inline const ::std::string& MALAtomField::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void MALAtomField::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MALAtomField::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MALAtomField::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mal.proto.MALAtomField.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void MALAtomField::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mal.proto.MALAtomField.name)
}

// int64 pos = 2;
inline void MALAtomField::clear_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pos_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::int64_t MALAtomField::pos() const {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtomField.pos)
  return _internal_pos();
}
inline void MALAtomField::set_pos(::int64_t value) {
  _internal_set_pos(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:mal.proto.MALAtomField.pos)
}
inline ::int64_t MALAtomField::_internal_pos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pos_;
}
inline void MALAtomField::_internal_set_pos(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pos_ = value;
}

// int32 bits = 3;
inline void MALAtomField::clear_bits() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bits_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::int32_t MALAtomField::bits() const {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtomField.bits)
  return _internal_bits();
}
inline void MALAtomField::set_bits(::int32_t value) {
  _internal_set_bits(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:mal.proto.MALAtomField.bits)
}
inline ::int32_t MALAtomField::_internal_bits() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bits_;
}
inline void MALAtomField::_internal_set_bits(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bits_ = value;
}

// string extra_val = 4;
inline void MALAtomField::clear_extra_val() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.extra_val_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& MALAtomField::extra_val() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtomField.extra_val)
  return _internal_extra_val();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MALAtomField::set_extra_val(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.extra_val_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mal.proto.MALAtomField.extra_val)
}
inline ::std::string* PROTOBUF_NONNULL MALAtomField::mutable_extra_val()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_extra_val();
  // @@protoc_insertion_point(field_mutable:mal.proto.MALAtomField.extra_val)
  return _s;
}
inline const ::std::string& MALAtomField::_internal_extra_val() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.extra_val_.Get();
}
inline void MALAtomField::_internal_set_extra_val(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.extra_val_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MALAtomField::_internal_mutable_extra_val() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.extra_val_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MALAtomField::release_extra_val() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mal.proto.MALAtomField.extra_val)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.extra_val_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.extra_val_.Set("", GetArena());
  }
  return released;
}
inline void MALAtomField::set_allocated_extra_val(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.extra_val_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.extra_val_.IsDefault()) {
    _impl_.extra_val_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mal.proto.MALAtomField.extra_val)
}

// int32 big = 5;
inline void MALAtomField::clear_big() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.big_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline ::int32_t MALAtomField::big() const {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtomField.big)
  return _internal_big();
}
inline void MALAtomField::set_big(::int32_t value) {
  _internal_set_big(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:mal.proto.MALAtomField.big)
}
inline ::int32_t MALAtomField::_internal_big() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.big_;
}
inline void MALAtomField::_internal_set_big(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.big_ = value;
}

// string value = 7;
inline void MALAtomField::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline const ::std::string& MALAtomField::value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtomField.value)
  return _internal_value();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MALAtomField::set_value(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.value_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mal.proto.MALAtomField.value)
}
inline ::std::string* PROTOBUF_NONNULL MALAtomField::mutable_value()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:mal.proto.MALAtomField.value)
  return _s;
}
inline const ::std::string& MALAtomField::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_.Get();
}
inline void MALAtomField::_internal_set_value(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MALAtomField::_internal_mutable_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.value_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MALAtomField::release_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mal.proto.MALAtomField.value)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.value_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.value_.Set("", GetArena());
  }
  return released;
}
inline void MALAtomField::set_allocated_value(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.value_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mal.proto.MALAtomField.value)
}

// int32 i32 = 8;
inline bool MALAtomField::has_i32() const {
  return typevalue_case() == kI32;
}
inline void MALAtomField::set_has_i32() {
  _impl_._oneof_case_[0] = kI32;
}
inline void MALAtomField::clear_i32() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (typevalue_case() == kI32) {
    _impl_.typevalue_.i32_ = 0;
    clear_has_typevalue();
  }
}
inline ::int32_t MALAtomField::i32() const {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtomField.i32)
  return _internal_i32();
}
inline void MALAtomField::set_i32(::int32_t value) {
  if (typevalue_case() != kI32) {
    clear_typevalue();
    set_has_i32();
  }
  _impl_.typevalue_.i32_ = value;
  // @@protoc_insertion_point(field_set:mal.proto.MALAtomField.i32)
}
inline ::int32_t MALAtomField::_internal_i32() const {
  if (typevalue_case() == kI32) {
    return _impl_.typevalue_.i32_;
  }
  return 0;
}

// int64 i64 = 9;
inline bool MALAtomField::has_i64() const {
  return typevalue_case() == kI64;
}
inline void MALAtomField::set_has_i64() {
  _impl_._oneof_case_[0] = kI64;
}
inline void MALAtomField::clear_i64() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (typevalue_case() == kI64) {
    _impl_.typevalue_.i64_ = ::int64_t{0};
    clear_has_typevalue();
  }
}
inline ::int64_t MALAtomField::i64() const {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtomField.i64)
  return _internal_i64();
}
inline void MALAtomField::set_i64(::int64_t value) {
  if (typevalue_case() != kI64) {
    clear_typevalue();
    set_has_i64();
  }
  _impl_.typevalue_.i64_ = value;
  // @@protoc_insertion_point(field_set:mal.proto.MALAtomField.i64)
}
inline ::int64_t MALAtomField::_internal_i64() const {
  if (typevalue_case() == kI64) {
    return _impl_.typevalue_.i64_;
  }
  return ::int64_t{0};
}

// uint32 ui32 = 10;
inline bool MALAtomField::has_ui32() const {
  return typevalue_case() == kUi32;
}
inline void MALAtomField::set_has_ui32() {
  _impl_._oneof_case_[0] = kUi32;
}
inline void MALAtomField::clear_ui32() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (typevalue_case() == kUi32) {
    _impl_.typevalue_.ui32_ = 0u;
    clear_has_typevalue();
  }
}
inline ::uint32_t MALAtomField::ui32() const {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtomField.ui32)
  return _internal_ui32();
}
inline void MALAtomField::set_ui32(::uint32_t value) {
  if (typevalue_case() != kUi32) {
    clear_typevalue();
    set_has_ui32();
  }
  _impl_.typevalue_.ui32_ = value;
  // @@protoc_insertion_point(field_set:mal.proto.MALAtomField.ui32)
}
inline ::uint32_t MALAtomField::_internal_ui32() const {
  if (typevalue_case() == kUi32) {
    return _impl_.typevalue_.ui32_;
  }
  return 0u;
}

// uint64 ui64 = 11;
inline bool MALAtomField::has_ui64() const {
  return typevalue_case() == kUi64;
}
inline void MALAtomField::set_has_ui64() {
  _impl_._oneof_case_[0] = kUi64;
}
inline void MALAtomField::clear_ui64() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (typevalue_case() == kUi64) {
    _impl_.typevalue_.ui64_ = ::uint64_t{0u};
    clear_has_typevalue();
  }
}
inline ::uint64_t MALAtomField::ui64() const {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtomField.ui64)
  return _internal_ui64();
}
inline void MALAtomField::set_ui64(::uint64_t value) {
  if (typevalue_case() != kUi64) {
    clear_typevalue();
    set_has_ui64();
  }
  _impl_.typevalue_.ui64_ = value;
  // @@protoc_insertion_point(field_set:mal.proto.MALAtomField.ui64)
}
inline ::uint64_t MALAtomField::_internal_ui64() const {
  if (typevalue_case() == kUi64) {
    return _impl_.typevalue_.ui64_;
  }
  return ::uint64_t{0u};
}

// double db = 12;
inline bool MALAtomField::has_db() const {
  return typevalue_case() == kDb;
}
inline void MALAtomField::set_has_db() {
  _impl_._oneof_case_[0] = kDb;
}
inline void MALAtomField::clear_db() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (typevalue_case() == kDb) {
    _impl_.typevalue_.db_ = 0;
    clear_has_typevalue();
  }
}
inline double MALAtomField::db() const {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtomField.db)
  return _internal_db();
}
inline void MALAtomField::set_db(double value) {
  if (typevalue_case() != kDb) {
    clear_typevalue();
    set_has_db();
  }
  _impl_.typevalue_.db_ = value;
  // @@protoc_insertion_point(field_set:mal.proto.MALAtomField.db)
}
inline double MALAtomField::_internal_db() const {
  if (typevalue_case() == kDb) {
    return _impl_.typevalue_.db_;
  }
  return 0;
}

// string strv = 13;
inline bool MALAtomField::has_strv() const {
  return typevalue_case() == kStrv;
}
inline void MALAtomField::set_has_strv() {
  _impl_._oneof_case_[0] = kStrv;
}
inline void MALAtomField::clear_strv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (typevalue_case() == kStrv) {
    _impl_.typevalue_.strv_.Destroy();
    clear_has_typevalue();
  }
}
inline const ::std::string& MALAtomField::strv() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtomField.strv)
  return _internal_strv();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MALAtomField::set_strv(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (typevalue_case() != kStrv) {
    clear_typevalue();

    set_has_strv();
    _impl_.typevalue_.strv_.InitDefault();
  }
  _impl_.typevalue_.strv_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mal.proto.MALAtomField.strv)
}
inline ::std::string* PROTOBUF_NONNULL MALAtomField::mutable_strv()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  if (typevalue_case() != kStrv) {
    clear_typevalue();

    set_has_strv();
    _impl_.typevalue_.strv_.InitDefault();
  }
  ::std::string* _s = _internal_mutable_strv();
  // @@protoc_insertion_point(field_mutable:mal.proto.MALAtomField.strv)
  return _s;
}
inline const ::std::string& MALAtomField::_internal_strv() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  if (typevalue_case() != kStrv) {
    return ::google::protobuf::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.typevalue_.strv_.Get();
}
inline void MALAtomField::_internal_set_strv(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typevalue_.strv_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MALAtomField::_internal_mutable_strv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.typevalue_.strv_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MALAtomField::release_strv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mal.proto.MALAtomField.strv)
  if (typevalue_case() != kStrv) {
    return nullptr;
  }
  clear_has_typevalue();
  return _impl_.typevalue_.strv_.Release();
}
inline void MALAtomField::set_allocated_strv(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (has_typevalue()) {
    clear_typevalue();
  }
  if (value != nullptr) {
    set_has_strv();
    _impl_.typevalue_.strv_.InitAllocated(value, GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mal.proto.MALAtomField.strv)
}

// .mal.proto.MDPFieldDisplayType type = 14;
inline void MALAtomField::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
}
inline ::mal::proto::MDPFieldDisplayType MALAtomField::type() const {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtomField.type)
  return _internal_type();
}
inline void MALAtomField::set_type(::mal::proto::MDPFieldDisplayType value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:mal.proto.MALAtomField.type)
}
inline ::mal::proto::MDPFieldDisplayType MALAtomField::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::mal::proto::MDPFieldDisplayType>(_impl_.type_);
}
inline void MALAtomField::_internal_set_type(::mal::proto::MDPFieldDisplayType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

inline bool MALAtomField::has_typevalue() const {
  return typevalue_case() != TYPEVALUE_NOT_SET;
}
inline void MALAtomField::clear_has_typevalue() {
  _impl_._oneof_case_[0] = TYPEVALUE_NOT_SET;
}
inline MALAtomField::TypevalueCase MALAtomField::typevalue_case() const {
  return MALAtomField::TypevalueCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// MALAtom

// string name = 1;
inline void MALAtom::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline const ::std::string& MALAtom::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtom.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MALAtom::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mal.proto.MALAtom.name)
}
inline ::std::string* PROTOBUF_NONNULL MALAtom::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:mal.proto.MALAtom.name)
  return _s;
}
inline const ::std::string& MALAtom::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void MALAtom::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MALAtom::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MALAtom::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mal.proto.MALAtom.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void MALAtom::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mal.proto.MALAtom.name)
}

// int64 pos = 2;
inline void MALAtom::clear_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pos_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::int64_t MALAtom::pos() const {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtom.pos)
  return _internal_pos();
}
inline void MALAtom::set_pos(::int64_t value) {
  _internal_set_pos(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:mal.proto.MALAtom.pos)
}
inline ::int64_t MALAtom::_internal_pos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pos_;
}
inline void MALAtom::_internal_set_pos(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pos_ = value;
}

// int64 size = 3;
inline void MALAtom::clear_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::int64_t MALAtom::size() const {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtom.size)
  return _internal_size();
}
inline void MALAtom::set_size(::int64_t value) {
  _internal_set_size(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:mal.proto.MALAtom.size)
}
inline ::int64_t MALAtom::_internal_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.size_;
}
inline void MALAtom::_internal_set_size(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_ = value;
}

// repeated .mal.proto.MALAtomField fields = 4;
inline int MALAtom::_internal_fields_size() const {
  return _internal_fields().size();
}
inline int MALAtom::fields_size() const {
  return _internal_fields_size();
}
inline void MALAtom::clear_fields() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fields_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::mal::proto::MALAtomField& MALAtom::fields(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtom.fields)
  return _internal_fields().Get(index);
}
inline ::mal::proto::MALAtomField* PROTOBUF_NONNULL MALAtom::mutable_fields(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:mal.proto.MALAtom.fields)
  return _internal_mutable_fields()->Mutable(index);
}
inline ::mal::proto::MALAtomField* PROTOBUF_NONNULL MALAtom::add_fields()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::mal::proto::MALAtomField* _add =
      _internal_mutable_fields()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:mal.proto.MALAtom.fields)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtomField>& MALAtom::fields() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:mal.proto.MALAtom.fields)
  return _internal_fields();
}
inline ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtomField>* PROTOBUF_NONNULL
MALAtom::mutable_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:mal.proto.MALAtom.fields)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_fields();
}
inline const ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtomField>&
MALAtom::_internal_fields() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fields_;
}
inline ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtomField>* PROTOBUF_NONNULL
MALAtom::_internal_mutable_fields() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.fields_;
}

// repeated .mal.proto.MALAtom child_boxes = 5;
inline int MALAtom::_internal_child_boxes_size() const {
  return _internal_child_boxes().size();
}
inline int MALAtom::child_boxes_size() const {
  return _internal_child_boxes_size();
}
inline void MALAtom::clear_child_boxes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.child_boxes_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::mal::proto::MALAtom& MALAtom::child_boxes(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtom.child_boxes)
  return _internal_child_boxes().Get(index);
}
inline ::mal::proto::MALAtom* PROTOBUF_NONNULL MALAtom::mutable_child_boxes(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:mal.proto.MALAtom.child_boxes)
  return _internal_mutable_child_boxes()->Mutable(index);
}
inline ::mal::proto::MALAtom* PROTOBUF_NONNULL MALAtom::add_child_boxes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::mal::proto::MALAtom* _add =
      _internal_mutable_child_boxes()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:mal.proto.MALAtom.child_boxes)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtom>& MALAtom::child_boxes() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:mal.proto.MALAtom.child_boxes)
  return _internal_child_boxes();
}
inline ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtom>* PROTOBUF_NONNULL
MALAtom::mutable_child_boxes() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:mal.proto.MALAtom.child_boxes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_child_boxes();
}
inline const ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtom>&
MALAtom::_internal_child_boxes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.child_boxes_;
}
inline ::google::protobuf::RepeatedPtrField<::mal::proto::MALAtom>* PROTOBUF_NONNULL
MALAtom::_internal_mutable_child_boxes() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.child_boxes_;
}

// int32 header_size = 6;
inline void MALAtom::clear_header_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.header_size_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline ::int32_t MALAtom::header_size() const {
  // @@protoc_insertion_point(field_get:mal.proto.MALAtom.header_size)
  return _internal_header_size();
}
inline void MALAtom::set_header_size(::int32_t value) {
  _internal_set_header_size(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:mal.proto.MALAtom.header_size)
}
inline ::int32_t MALAtom::_internal_header_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.header_size_;
}
inline void MALAtom::_internal_set_header_size(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.header_size_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace mal


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::mal::proto::MDPFieldDisplayType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::mal::proto::MDPFieldDisplayType>() {
  return ::mal::proto::MDPFieldDisplayType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // atom_2eproto_2epb_2eh
