#ifndef MDP_MEDIAERROR__H
#define MDP_MEDIAERROR__H

#define MDP_ERROR_BASE         (-30000)    //从-30000开始
#define MDP_ERROR_CODES(X) \
X(-1 + MDP_ERROR_BASE, MDPERROR_PARSER_NOT_FOUND, "MDPERROR_PARSER_NOT_FOUND", "paser not found") \
X(-2 + MDP_ERROR_BASE, MDPERROR_DATASOURCE_NOT_FOUND, "MDPERROR_DATASOURCE_NOT_FOUND", "datasource not found") \
X(-3 + MDP_ERROR_BASE, MDPERROR_DATASOURCE_OPEN_FAIL, "MDPERROR_DATASOURCE_OPEN_FAIL", "datasource open fail") \
X(-4 + MDP_ERROR_BASE, MDPERROR_DATASOURCE_READ_FAIL, "MDPERROR_DATASOURCE_READ_FAIL", "datasource read fail") \
X(-5 + MDP_ERROR_BASE, MDPERROR_DATASOURCE_INVAL_URL, "MDPERROR_DATASOURCE_INVAL_URL", "文件输入路径不合法") \
X(-6 + MDP_ERROR_BASE, MDPERROR_DATASOURCE_chunk_OUT_BOUNDS, "MDPERROR_DATASOURCE_chunk_OUT_BOUNDS", "chunk index is out bounds") \
X(-7 + MDP_ERROR_BASE, MDPERROR_NOMEM, "MDPERROR_NOMEM", "system no memory") \
X(-8 + MDP_ERROR_BASE, MDPERROR_EOF, "MDPERROR_EOF", "eof") \
X(-9 + MDP_ERROR_BASE, MDPERROR_FIND_CHUNK_FAIL, "MDPERROR_FIND_CHUNK_FAIL", "find track fial") \
X(-10 + MDP_ERROR_BASE, MDPERROR_DATASOURCE_INVAL, "MDPERROR_DATASOURCE_INVAL", "PARAM INVAL") \
X(-11 + MDP_ERROR_BASE, MDPERROR_STREAM_INDEX_INVAL, "MDPERROR_STREAM_INDEX_INVAL", "PARAM INVAL") \

#define MDP_ERROR_ENUM(ID, NAME, ERR_MSG, ERR_DESC) NAME = ID,
enum {
    MDP_ERROR_CODES(MDP_ERROR_ENUM)
};
const char* mdp_error_msg(int error);

#endif